# Generated by Django 4.1.3 on 2022-11-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.IntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C')], help_text='질문그룹', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_column',
            field=models.IntegerField(blank=True, choices=[(0, '신체'), (1, '인지'), (2, '언어'), (3, '정서'), (4, '사회성'), (5, '자폐'), (6, 'Adhd')], help_text='규준표 컬럼', null=True),
        ),
    ]
