# Generated by Django 4.1.3 on 2022-11-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_question_group_alter_question_test_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='질문그룹', max_length=1, null=True),
        ),
    ]
