# Generated by Django 4.1.3 on 2022-12-01 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='이름', max_length=10, null=True)),
                ('birthDate', models.DateField(blank=True, help_text='생년월일', null=True)),
                ('email', models.EmailField(blank=True, help_text='이메일', max_length=254, null=True)),
                ('privacy_agree', models.BooleanField(default=False, help_text='개인정보수집동의')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='이름', max_length=10, null=True)),
                ('birthDate', models.DateField(blank=True, help_text='생년월일', null=True)),
                ('residence', models.CharField(blank=True, help_text='거주지역', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자')], help_text='성별', max_length=1, null=True)),
                ('kindergarden', models.CharField(blank=True, help_text='유치원 이름', max_length=20, null=True)),
                ('testDate', models.DateTimeField(blank=True, help_text='검사일', null=True)),
                ('tester', models.ForeignKey(blank=True, help_text='검사자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='user.tester')),
            ],
        ),
    ]
