# Generated by Django 4.1.3 on 2022-12-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_child_testdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncheonRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(blank=True, help_text='시', max_length=10, null=True)),
                ('gu', models.CharField(blank=True, help_text='구/군', max_length=10, null=True)),
                ('emd', models.CharField(blank=True, help_text='읍면동', max_length=10, null=True)),
            ],
        ),
    ]
